import os
import base64
from xhtml2pdf import pisa
from io import BytesIO

class PDFService:
    @staticmethod
    def _read_file_as_base64(path):
        """Helper to convert image to base64 for embedding in HTML"""
        try:
            with open(path, "rb") as image_file:
                return base64.b64encode(image_file.read()).decode("utf-8")
        except Exception as e:
            print(f"⚠️ Image read error ({path}): {e}")
            return None

    @staticmethod
    def generate_report(results, chart_map=None):
        """
        Generates a PDF report from a list of HTML content chunks.
        results: List of dicts, e.g. [{"category": "finance", "content": "<div>...</div>"}]
        chart_map: Dict mapping category -> chart_path
        """
        if not chart_map:
            chart_map = {}

        # 1. Master CSS Template
        css = """
        <style>
            @page {
                size: A4;
                margin: 2cm;
                @frame footer_frame {
                    -pdf-frame-content: footerContent;
                    bottom: 1cm;
                    margin-left: 2cm;
                    margin-right: 2cm;
                    height: 1cm;
                }
            }
            body { font-family: Helvetica, sans-serif; font-size: 12px; line-height: 1.5; }
            .page-break { page-break-after: always; }
            
            h1 { color: #2c3e50; font-size: 24px; text-align: center; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; }
            h2 { color: #e74c3c; font-size: 18px; margin-top: 20px; border-left: 5px solid #e74c3c; padding-left: 10px; }
            
            .card { border: 1px solid #ddd; background-color: #f9f9f9; padding: 15px; margin-bottom: 15px; border-radius: 5px; }
            .item-title { font-weight: bold; font-size: 14px; color: #34495e; margin-bottom: 10px; }
            
            table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
            th, td { border: 1px solid #ccc; padding: 8px; text-align: left; vertical-align: top; }
            th { background-color: #eee; }
            
            .alert { background-color: #fff3cd; color: #856404; padding: 10px; border: 1px solid #ffeeba; border-radius: 4px; margin-top: 5px; font-style: italic; }
            .motto { text-align: center; font-style: italic; color: #555; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; }
            
            .chart-container { text-align: center; margin: 20px 0; }
            .chart-img { max-width: 100%; height: auto; border: 1px solid #ddd; padding: 5px; }
        </style>
        """

        # 2. Build HTML Content
        html_body = "<body>"
        
        # Title Page
        html_body += """
        <div style="text-align: center; padding-top: 5cm;">
            <h1>BÁO CÁO CHIẾN LƯỢC NGÀY</h1>
            <p>Generated by Daily-Bot AI</p>
            <p>Date: %s</p>
        </div>
        <div class="page-break"></div>
        """ % (import_datetime_now())

        # Category Pages
        # Order priorities if needed, or stick to list order
        for res in results:
            cat = res.get("category", "unknown").upper()
            content = res.get("content", "")
            
            # Start New Page per Category
            html_body += f"""
            <div class="category-section">
                <h1>{cat} REPORT</h1>
                {content}
            </div>
            """
            
            # Embed Chart if available for this category
            c_path = chart_map.get(res.get("category"))
            if c_path and os.path.exists(c_path):
                b64_img = PDFService._read_file_as_base64(c_path)
                if b64_img:
                    html_body += f"""
                    <div class="chart-container">
                        <h3>Biểu đồ {cat}</h3>
                        <img class="chart-img" src="data:image/png;base64,{b64_img}" />
                    </div>
                    """
            
            # Page Break after specific sections or all
            html_body += '<div class="page-break"></div>'

        # Close Body
        html_body += """
        <div id="footerContent" style="text-align:center; font-size: 10px;">
            Confidential Report - Internal Use Only
        </div>
        </body>
        """

        full_html = css + html_body

        # 3. Generate PDF
        output_dir = "output"
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        pdf_path = os.path.join(output_dir, "Daily_Report.pdf")
        
        try:
            with open(pdf_path, "wb") as pdf_file:
                pisa_status = pisa.CreatePDF(full_html, dest=pdf_file)
                
            if pisa_status.err:
                print(f"❌ PDF Generation Error: {pisa_status.err}")
                return None
                
            return pdf_path
        except Exception as e:
             print(f"❌ PDF Write Error: {e}")
             return None

def import_datetime_now():
    from datetime import datetime
    import pytz
    vn_tz = pytz.timezone('Asia/Ho_Chi_Minh')
    return datetime.now(vn_tz).strftime('%d/%m/%Y %H:%M')
